services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gw2
      POSTGRES_PASSWORD: gw2
      POSTGRES_DB: gw2pvp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
